"""
Pydantic data models — the canonical data shapes used across the entire agent.
Every module speaks in these types; no raw dicts passed between layers.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


def _utcnow() -> datetime:
    """Timezone-aware UTC now. Replaces deprecated datetime.utcnow()."""
    return datetime.now(timezone.utc)


# ── Quote (single price tick) ─────────────────────────────────────────────────

class Quote(BaseModel):
    """A single OHLCV data point."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float | None = None       # populated by technical layer


# ── Fundamentals ──────────────────────────────────────────────────────────────

class Fundamentals(BaseModel):
    """Key fundamental metrics for a stock / ETF."""
    market_cap: float | None = None          # in local currency (INR / USD)
    pe_ratio: float | None = None
    pb_ratio: float | None = None
    eps: float | None = None
    revenue_ttm: float | None = None         # trailing 12-month revenue
    net_income_ttm: float | None = None
    ebitda: float | None = None
    debt_to_equity: float | None = None
    free_cash_flow: float | None = None
    dividend_yield: float | None = None
    beta: float | None = None
    week_52_high: float | None = None
    week_52_low: float | None = None
    avg_volume_30d: int | None = None
    shares_outstanding: float | None = None
    return_on_equity: float | None = None
    profit_margin: float | None = None


# ── News Item ─────────────────────────────────────────────────────────────────

class NewsItem(BaseModel):
    """A single news headline."""
    title: str
    publisher: str | None = None
    published_at: datetime | None = None
    url: str | None = None
    summary: str | None = None              # LLM-generated 1-sentence summary
    sentiment: Literal["positive", "neutral", "negative"] | None = None


# ── Stock Snapshot (main data object passed to analyst) ───────────────────────

class StockSnapshot(BaseModel):
    """
    Complete data snapshot for a single ticker.
    This is the primary input to the analyst engine.
    """
    ticker: str
    name: str | None = None
    market: Literal["india", "us"]
    sector: str | None = None
    currency: Literal["INR", "USD"]
    is_etf: bool = False                    # set explicitly by fetcher (not guessed)

    # Current price info
    current_price: float
    price_change_pct_1d: float | None = None
    price_change_pct_1w: float | None = None
    price_change_pct_1m: float | None = None
    price_change_pct_3m: float | None = None
    price_change_pct_1y: float | None = None

    # OHLCV history (most recent ~252 trading days for technical analysis)
    history: list[Quote] = Field(default_factory=list)

    # Fundamentals
    fundamentals: Fundamentals = Field(default_factory=Fundamentals)

    # News
    recent_news: list[NewsItem] = Field(default_factory=list)

    # Metadata
    fetched_at: datetime = Field(default_factory=_utcnow)
    data_source: str = "yfinance"

    @field_validator("ticker")
    @classmethod
    def uppercase_ticker(cls, v: str) -> str:
        return v.upper()

    def price_summary(self) -> str:
        """One-line price summary for logging / quick display."""
        currency_sym = "₹" if self.currency == "INR" else "$"
        chg = f"{self.price_change_pct_1d:+.2f}%" if self.price_change_pct_1d is not None else "N/A"
        return f"{self.ticker} @ {currency_sym}{self.current_price:,.2f} ({chg} today)"


Strategy = Literal["scalping", "intraday", "swing", "positional"]


# ── Trade Signal ──────────────────────────────────────────────────────────────

class TradeSignal(BaseModel):
    """A trading signal generated by the signal engine."""
    model_config = ConfigDict(strict=True)

    ticker: str
    market: Literal["india", "us"]
    strategy: Strategy
    direction: Literal["BUY", "SELL", "HOLD"]
    entry_price: float
    stop_loss: float
    target_price: float
    quantity: int
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    generated_at: datetime = Field(default_factory=_utcnow)
    expires_at: datetime | None = None


# ── Paper / Live Order ────────────────────────────────────────────────────────

class Order(BaseModel):
    """A paper or live order."""
    model_config = ConfigDict(strict=True)

    order_id: str
    ticker: str
    market: Literal["india", "us"]
    strategy: Strategy
    order_type: Literal["MARKET", "LIMIT", "SL", "SL-M"]
    direction: Literal["BUY", "SELL"]
    quantity: int
    limit_price: float | None = None
    trigger_price: float | None = None
    filled_price: float | None = None
    status: Literal["PENDING", "OPEN", "FILLED", "CANCELLED", "REJECTED"] = "PENDING"
    is_paper: bool = True
    created_at: datetime = Field(default_factory=_utcnow)
    filled_at: datetime | None = None


# ── Position ──────────────────────────────────────────────────────────────────

class Position(BaseModel):
    """An open position in the portfolio."""
    ticker: str
    market: Literal["india", "us"]
    strategy: Strategy
    direction: Literal["LONG", "SHORT"]
    quantity: int
    avg_cost: float
    current_price: float | None = None
    stop_loss: float | None = None
    target_price: float | None = None
    is_paper: bool = True
    opened_at: datetime = Field(default_factory=_utcnow)

    @property
    def unrealized_pnl(self) -> float | None:
        if self.current_price is None:
            return None
        if self.direction == "LONG":
            return (self.current_price - self.avg_cost) * self.quantity
        return (self.avg_cost - self.current_price) * self.quantity

    @property
    def unrealized_pnl_pct(self) -> float | None:
        if self.current_price is None or self.avg_cost == 0:
            return None
        if self.direction == "LONG":
            return ((self.current_price - self.avg_cost) / self.avg_cost) * 100
        return ((self.avg_cost - self.current_price) / self.avg_cost) * 100


# ── Advisory Holding ──────────────────────────────────────────────────────────

class AdvisoryHolding(BaseModel):
    """An advisory portfolio holding (recommended, not auto-executed)."""
    ticker: str
    name: str | None = None
    market: Literal["india", "us"]
    horizon: Literal["short_term", "long_term"]
    entry_price: float
    recommended_at: datetime
    quantity_suggested: int | None = None
    stop_loss: float | None = None
    target_price: float | None = None
    current_price: float | None = None
    thesis: str | None = None
    invalidation_trigger: str | None = None

    @property
    def return_pct(self) -> float | None:
        if self.current_price is None or self.entry_price == 0:
            return None
        return ((self.current_price - self.entry_price) / self.entry_price) * 100

    @property
    def days_held(self) -> int:
        return (datetime.now(timezone.utc) - self.recommended_at.replace(tzinfo=timezone.utc)).days


# ── LLM Analyst Output ────────────────────────────────────────────────────────

class StockAnalysis(BaseModel):
    """Structured output from the LLM analyst — enforced schema."""
    ticker: str
    risk_level: Literal["Low", "Medium", "High"]
    action: Literal["Must Buy", "Good Buy", "Hold-Watch", "Must Avoid"]
    reasons_attractive: list[str] = Field(min_length=1, max_length=5)
    risks: list[str] = Field(min_length=1, max_length=5)
    suggested_approach: str
    invalidation_trigger: str
    entry_price_hint: float | None = None
    stop_loss_hint: float | None = None
    target_price_hint: float | None = None
    confidence_score: float = Field(ge=0.0, le=1.0)
    strategy_fit: list[Strategy]
    horizon_fit: list[Literal["short_term", "long_term"]]
    analyst_notes: str | None = None


# ── Trade Playbook / Learning Autopsy ─────────────────────────────────────────

class TradePlaybookEntry(BaseModel):
    """An autopsy record of a completed trade for continuous learning."""
    id: int | None = None
    ticker: str
    market: Literal["india", "us"]
    strategy: Strategy
    direction: Literal["BUY", "SELL"]
    entry_price: float
    exit_price: float
    realized_pnl: float
    realized_pnl_pct: float
    failure_category: str = "PROFITABLE"
    root_cause: str = ""
    prescriptive_lesson: str = ""
    created_at: datetime = Field(default_factory=_utcnow)
